name: VirtualStorage
version: '${project.version}'
main: com.example.virtualstorage.VirtualStorage
api-version: '1.21'
authors: [YourName]
description: Virtual storage plugin for Minecraft servers
commands:
  storage:
    description: Main command for virtual storage
    usage: /storage <open|add> [player] [item] [amount]
    permission: storage.use
permissions:
  storage.use:
    description: Allows players to use their own storage
    default: true
  storage.admin:
    description: Allows administrators to manage all storages
    default: op 